name: Check

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build
    runs-on: sonarqube
    permissions: read-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Install Dependencies
        run: npm install --no-progress --no-fund --prefer-offline --legacy-peer-deps

      - name: Check packages
        run: |
          npm audit --audit-level=none
          npm outdated || code=$?; if [ $code -eq 1 ]; then echo 0; else echo $code; fi
          node_modules/.bin/eslint -f json **/*.ts -o eslint_report.json --report-unused-disable-directives --exit-on-fatal-error || code=$?; if [ $code -eq 2 ]; then echo 0; else echo $code; fi

      - name: Dependency check
        env:
          NVDAPIKEY: ${{ secrets.NVDAPIKEY }}
        run: dependency-check.sh --exclude .sonar/ --exclude .scannerwork/ --exclude .git/ --out . --scan . --nvdApiKey "$NVDAPIKEY"

      - name: Sonar scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: NODE_OPTIONS="--max-old-space-size=4096" NODE_ENV=production sonar-scanner
